---
title: Don't collide!
hero_image: images/banner.png
description: Build an endless runner game where your character must avoid colliding with obstacles
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Introduction
  - 
    title: Set the theme
  - 
    title: Create obstacles
    completion: engaged
  - 
    title: Collision detection
  - 
    title: Speed up!
    completion: internal
  - 
    title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Upgrade your project
    completion: external
  - 
    title: Share
  - 
    title: What next?
