---
title: Non scontrarti!
hero_image: images/banner.png
description:
  - Costruisci un gioco senza fine in cui il tuo corridore deve evitare di scontrarsi
  - con ostacoli
meta_title: Progetti di programmazione Python per bambini e ragazzi | Non scontrarti!
meta_description: Impara Python con i progetti di programmazione della Raspberry Pi Foundation per bambini e ragazzi. Costruisci un gioco per far scorrere il tuo corridore in Python ed evitare gli ostacoli.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Quello che farai
  - title: Prepara la scena
  - title: Crea gli ostacoli
    completion:
      - engaged
  - title: Rilevamento delle collisioni
  - title: Accelera!
    completion:
      - internal
  - title: Quiz veloce
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Migliora il tuo progetto
  - title: Condividi
  - title: E adesso?
